// FinTrack redesign prototype — sample data and the feature-coverage inventory.
// Everything here is invented example data. Nothing connects to real accounts.
'use strict';

const TODAY = new Date(2026, 9, 5); // 5 Oct 2026 (sample "today")

function d(day, month = 9, hour = 12) { return new Date(2026, month, day, hour); }

const CATS = {
  groceries:    { name: 'Groceries',      icon: '🛒', color: 'var(--cat-teal)' },
  dining:       { name: 'Dining',         icon: '🍽', color: 'var(--cat-coral)' },
  transport:    { name: 'Transport',      icon: '🚗', color: 'var(--cat-blue)' },
  utilities:    { name: 'Utilities',      icon: '💡', color: 'var(--cat-gold)' },
  shopping:     { name: 'Shopping',       icon: '🛍', color: 'var(--cat-purple)' },
  entertainment:{ name: 'Entertainment',  icon: '🎬', color: 'var(--cat-coral)' },
  health:       { name: 'Health',         icon: '🩺', color: 'var(--cat-teal)' },
  housing:      { name: 'Housing',        icon: '🏠', color: 'var(--cat-blue)' },
  salary:       { name: 'Salary',         icon: '💼', color: 'var(--income)' },
  freelance:    { name: 'Freelance',      icon: '🧑‍💻', color: 'var(--income)' },
  transfer:     { name: 'Transfer',       icon: '⇄', color: 'var(--text-2)' },
  loan:         { name: 'Loan repayment', icon: '🏦', color: 'var(--cat-blue)' },
  subscriptions:{ name: 'Subscriptions',  icon: '🔁', color: 'var(--cat-purple)' },
};

const SAMPLE = {
  profile: { name: 'Mohammad', base: 'AED' },
  accounts: [
    { id: 'a1', name: 'Emirates NBD Current', kind: 'Bank', group: 'Cash & bank', balance: 18450.75, cur: 'AED', last4: '4821' },
    { id: 'a2', name: 'ADCB Savings', kind: 'Savings', group: 'Cash & bank', balance: 42000, cur: 'AED', last4: '0917' },
    { id: 'a3', name: 'Wise USD', kind: 'Bank', group: 'Cash & bank', balance: 1250, cur: 'USD', last4: '5520' },
    { id: 'a4', name: 'Cash wallet', kind: 'Cash', group: 'Cash & bank', balance: 650, cur: 'AED' },
    { id: 'a5', name: 'FAB Visa Platinum', kind: 'Credit card', group: 'Credit cards', balance: -3240.5, cur: 'AED', limit: 25000, due: d(18), last4: '7702' },
  ],
  transactions: [
    { id: 't1', title: 'Carrefour', cat: 'groceries', amount: -312.4, cur: 'AED', date: d(5, 9, 18), acct: 'a1', method: 'Card' },
    { id: 't2', title: 'ENOC', cat: 'transport', amount: -180, cur: 'AED', date: d(5, 9, 8), acct: 'a5', method: 'Card' },
    { id: 't3', title: 'Talabat', cat: 'dining', amount: -86.5, cur: 'AED', date: d(4, 9, 21), acct: 'a5', method: 'Apple Pay', tags: ['family'] },
    { id: 't4', title: 'Salik top-up', cat: 'transport', amount: -100, cur: 'AED', date: d(4, 9, 9), acct: 'a1', method: 'Card' },
    { id: 't5', title: 'Starbucks', cat: 'dining', amount: -28, cur: 'AED', date: d(4, 9, 8), acct: 'a4', method: 'Cash' },
    { id: 't6', title: 'iCloud+', cat: 'subscriptions', amount: -2.99, cur: 'USD', date: d(3, 9, 7), acct: 'a3', method: 'Card', recurring: 'Monthly' },
    { id: 't7', title: 'Noon — headphones', cat: 'shopping', amount: -349, cur: 'AED', date: d(3, 9, 15), acct: 'a5', method: 'BNPL', bnpl: 'b1' },
    { id: 't8', title: 'Lulu Hypermarket', cat: 'groceries', amount: -156.25, cur: 'AED', date: d(2, 9, 19), acct: 'a1', method: 'Card' },
    { id: 't9', title: 'Transfer to savings', cat: 'transfer', amount: -3000, cur: 'AED', date: d(1, 9, 10), acct: 'a1', to: 'a2', method: 'Transfer' },
    { id: 't10', title: 'Car loan EMI', cat: 'loan', amount: -2150, cur: 'AED', date: d(1, 9, 9), acct: 'a1', method: 'Transfer', loan: 'l1' },
    { id: 't11', title: 'Salary — Al Futtaim', cat: 'salary', amount: 24000, cur: 'AED', date: d(28, 8, 9), acct: 'a1', method: 'Transfer' },
    { id: 't12', title: 'DEWA', cat: 'utilities', amount: -640.3, cur: 'AED', date: d(27, 8, 11), acct: 'a1', method: 'Card', bill: 'bl1' },
    { id: 't13', title: 'du Mobile', cat: 'utilities', amount: -299, cur: 'AED', date: d(26, 8, 10), acct: 'a5', method: 'Card', bill: 'bl2' },
    { id: 't14', title: 'Careem', cat: 'transport', amount: -42, cur: 'AED', date: d(26, 8, 22), acct: 'a5', method: 'Apple Pay' },
    { id: 't15', title: 'Al Noor Café website', cat: 'freelance', amount: 4250, cur: 'AED', date: d(24, 8, 14), acct: 'a1', method: 'Transfer' },
    { id: 't16', title: 'VOX Cinemas', cat: 'entertainment', amount: -120, cur: 'AED', date: d(23, 8, 20), acct: 'a5', method: 'Card', split: true },
    { id: 't17', title: 'Aster Pharmacy', cat: 'health', amount: -64.75, cur: 'AED', date: d(22, 8, 12), acct: 'a4', method: 'Cash' },
    { id: 't18', title: 'Rent — October', cat: 'housing', amount: -7500, cur: 'AED', date: d(1, 9, 8), acct: 'a1', method: 'Cheque', pending: true },
  ],
  review: [
    { id: 'r1', merchant: 'Carrefour MOE', amount: 214.6, cur: 'AED', type: 'Expense', cat: 'groceries', when: d(5, 9, 19), channel: 'Email', source: 'Emirates NBD alert', confidence: 0.96, acct: 'a1', card: '4821' },
    { id: 'r2', merchant: 'ENOC 1043', amount: 95, cur: 'AED', type: 'Expense', cat: 'transport', when: d(5, 9, 7), channel: 'SMS', source: 'FAB SMS', confidence: 0.92, acct: 'a5', card: '7702' },
    { id: 'r3', merchant: 'Noon', amount: 349, cur: 'AED', type: 'Expense', cat: 'shopping', when: d(3, 9, 15), channel: 'Apple Pay', source: 'Wallet automation', confidence: 0.95, acct: 'a5', bnplNeeded: true },
    { id: 'r4', merchant: 'Talabat', amount: 86.5, cur: 'AED', type: 'Expense', cat: 'dining', when: d(4, 9, 21), channel: 'Email', source: 'FAB alert', confidence: 0.81, acct: 'a5', duplicateOf: 't3' },
  ],
  budgets: [
    { id: 'bu1', cat: 'groceries', limit: 2000, spent: 1240 },
    { id: 'bu2', cat: 'dining', limit: 1200, spent: 1056 },
    { id: 'bu3', cat: 'transport', limit: 900, spent: 410 },
    { id: 'bu4', cat: 'shopping', limit: 1500, spent: 1620 },
    { id: 'bu5', cat: 'entertainment', limit: 400, spent: 120 },
  ],
  envelopes: [ { name: 'Holiday — Georgia', balance: 3200, target: 6000 }, { name: 'Car service', balance: 850, target: 1200 } ],
  bills: [
    { id: 'bl2', name: 'du Mobile', amount: 299, due: d(8), cycle: 'Monthly', sub: false, auto: true, cat: 'utilities' },
    { id: 'bl1', name: 'DEWA', amount: 640.3, due: d(14), cycle: 'Monthly', sub: false, auto: false, cat: 'utilities', priceChange: '+8% vs last month' },
    { id: 'bl3', name: 'Netflix', amount: 56, due: d(22), cycle: 'Monthly', sub: true, auto: true, cat: 'subscriptions' },
    { id: 'bl4', name: 'Spotify Family', amount: 32.99, due: d(25), cycle: 'Monthly', sub: true, auto: true, cat: 'subscriptions', unused: '41 days since last use' },
    { id: 'bl5', name: 'Fitness First', amount: 250, due: d(30), cycle: 'Monthly', sub: true, auto: true, cat: 'health' },
    { id: 'bl6', name: 'Rent', amount: 7500, due: d(1, 10), cycle: 'Monthly', sub: false, auto: false, cat: 'housing' },
  ],
  goals: [
    { id: 'g1', name: 'Emergency fund', target: 30000, saved: 18500, perMonth: 1500, kind: 'Emergency' },
    { id: 'g2', name: 'Hajj 2027', target: 25000, saved: 6200, perMonth: 1600, kind: 'Hajj / Umrah' },
    { id: 'g3', name: 'Car down payment', target: 40000, saved: 12000, perMonth: 2000, kind: 'Down payment' },
  ],
  loans: [ { id: 'l1', name: 'Car loan — ENBD', outstanding: 54300, emi: 2150, rate: 3.49, next: d(12), paid: 19, total: 48 } ],
  bnpl: [ { id: 'b1', provider: 'tabby', name: 'Noon — headphones', installment: 349, paid: 2, total: 4, next: d(9) } ],
  lent: [ { id: 'm1', person: 'Ahmed', amount: 500, due: d(20) } ],
  borrowed: [ { id: 'm2', person: 'Sara', amount: 1200, due: d(30) } ],
  income: { salary: { employer: 'Al Futtaim', amount: 24000, day: 28, onTime: '11 of 12 on time' },
    freelance: [ { name: 'Al Noor Café website', value: 8500, paid: 4250 } ],
    rental: [ { name: 'Studio — Dubai Marina', rent: 5200, status: 'Occupied' } ],
    dividends: [ { name: 'Emaar Properties', amount: 312, date: d(15, 8) } ] },
  investments: [
    { id: 'i1', name: 'Vanguard FTSE All-World', symbol: 'VWRA', kind: 'ETF', value: 38420, change: 6.8 },
    { id: 'i2', name: 'Apple', symbol: 'AAPL', kind: 'Stock', value: 14210, change: 12.4 },
    { id: 'i3', name: 'Emaar Properties', symbol: 'EMAAR', kind: 'Stock', value: 9860, change: -2.1 },
    { id: 'i4', name: 'Bitcoin', symbol: 'BTC', kind: 'Crypto', value: 15120, change: 18.9 },
    { id: 'i5', name: 'Gold — 50 g, 22K', symbol: 'XAU', kind: 'Gold', value: 21350, change: 9.3 },
  ],
  assets: [
    { name: 'Apartment — JVC', kind: 'Real estate', value: 1100000, owed: 620000 },
    { name: 'Toyota Camry 2022', kind: 'Vehicle', value: 78000 },
    { name: 'Rolex Datejust', kind: 'Personal', value: 32000 },
    { name: 'Domain portfolio', kind: 'Digital', value: 4500 },
  ],
  rewards: [
    { name: 'Emirates Skywards', kind: 'Loyalty', value: '48,200 miles', est: 1928 },
    { name: 'SHARE (Majid Al Futtaim)', kind: 'Loyalty', value: '12,400 points', est: 124 },
    { name: 'Noon gift card', kind: 'Gift card', value: 'AED 200.00', est: 200, expires: 'Expires 31 Dec' },
  ],
  family: { group: 'Al Mansoori household', members: ['Mohammad (you)', 'Layla', 'Omar (child)'] },
  emailAccounts: [ { addr: 'm•••@gmail.com', provider: 'Gmail', last: '12 min ago' } ],
  bankRules: [ { bank: 'Emirates NBD', sender: 'alerts@emiratesnbd.com' }, { bank: 'FAB', sender: 'SMS: FAB' } ],
};

const FX = { AED: 1, USD: 3.6725, EUR: 3.98, GBP: 4.66 };

// ---------------------------------------------------------------------------
// Feature coverage matrix. `go` is the prototype route that demonstrates it.
// Kept here so the in-prototype matrix and the README stay one list.
// ---------------------------------------------------------------------------
const FEATURES = [
  // Area, feature, current entry point, UX problem, proposed entry point, route
  ['Home', 'Monthly overview (income, spending, savings rate, spending donut)', 'Dashboard tab', 'Header has three unlabelled icon buttons (AI, Reports, Profile); no clear primary action', 'Home tab — summary card first, labelled shortcuts', 'home'],
  ['Home', 'Account cards row', 'Dashboard (tapping switches tab)', 'Tapping a card silently switches tabs instead of opening the account', 'Home → account opens Account detail', 'home'],
  ['Home', 'Upcoming payments (loans, cards, BNPL, bills, borrowed)', 'Dashboard → sheet', 'Second "bills" card duplicates it', 'Home → Coming up → Upcoming (pushed)', 'upcoming'],
  ['Home', 'Smart insights cards', 'Dashboard', 'Separate from the AI hub and from Financial Intelligence', 'Home → Insights (one hub)', 'insights'],
  ['Home', 'Customise dashboard sections', 'Settings → Dashboard Layout', 'Lives three levels away from Home', 'Home → Edit Home (bottom of Home) and Settings → Home screen', 'home-edit'],
  ['Entry', 'Add expense / income / transfer', 'Centre "+" in a custom tab bar', 'Icon-only, custom non-native bar', 'Labelled "Add transaction" bar above the tab bar (iPhone) / toolbar button (wide)', 'sheet:add'],
  ['Entry', 'Receipt scan (OCR), voice entry', 'Inside the Add form', 'Found only after opening the long form', 'First row of the Add sheet: Scan receipt · Dictate', 'sheet:add'],
  ['Entry', 'Split, recurring, tags, location, pending/scheduled, tax flags, loyalty points, payment method (cheque, BNPL, bill link), attachments', 'Add form (one long screen)', 'Everything shown at once', '"More details" grouped sections in the Add sheet', 'sheet:add'],
  ['Entry', 'Unsaved-changes protection, duplicate warning, balance check', 'Add form', '—', 'Kept; shown inline at the Save button', 'sheet:add'],
  ['Activity', 'Transaction list grouped by day, search', 'Transactions tab', 'Search covers title/category/merchant only', 'Activity tab with search, scopes and filters', 'activity'],
  ['Activity', 'Type and date-range filters', 'Chips + date sheet', '—', 'Filter button (shows count) → Filter sheet', 'activity'],
  ['Activity', 'Delete with Undo, bulk delete/category/tag', 'Swipe; Edit mode', 'Delete is gesture-only', 'Row "More" menu + swipe; Select in toolbar', 'activity'],
  ['Activity', 'Transaction detail (FX rate, splits, receipt, attachments) and edit', 'Tap row', '—', 'Same', 'txn:t7'],
  ['Activity', 'Duplicate transactions banner', 'Transactions tab banner', '—', 'Filter "Possible duplicates"', 'activity'],
  ['Review', 'Review queue for email, SMS and Apple Pay imports', 'Banner inside Transactions; tab badge', 'The core pipeline is reached only through a banner; actions explained as gestures', '"To review" card on Home + section at top of Activity; visible Approve / Edit buttons', 'review'],
  ['Review', 'Approve all high-confidence, multi-select, reject all, history', 'Review queue', '—', 'Same, labelled buttons', 'review'],
  ['Review', 'Gates: BNPL plan, loan link, possible duplicate, "I paid for someone"', 'Edit sheet / dialogs', 'Blocked rows don\'t say why until tapped', 'Each blocked row states what it needs', 'review'],
  ['Import', 'Import & Sync hub', 'Settings → Import & Integration', 'Far from the ledger it feeds', 'Activity → Import, and Settings → Import & Sync', 'import'],
  ['Import', 'Email accounts (Gmail, Outlook, iCloud, IMAP), bank rules, paste email, sample emails', 'Import → Email', '—', 'Import → Bank emails', 'import-email'],
  ['Import', 'SMS automation via Shortcuts, SMS bank rules', 'Import → SMS', 'Setup steps are dense text', 'Import → Bank SMS (step list)', 'import-sms'],
  ['Import', 'Apple Pay automation via Shortcuts', 'Import → Apple Pay', '—', 'Import → Apple Pay', 'import-applepay'],
  ['Import', 'CSV import with column mapping', 'Import hub', '—', 'Import → Spreadsheet (CSV)', 'import-csv'],
  ['Import', 'OFX / QFX / QIF statement import', 'Import hub', '—', 'Import → Bank statement file', 'import-ofx'],
  ['Plan', 'Budgets — monthly, annual, envelopes, zero-based', 'Budget tab (4 inner tabs)', 'Toolbar menu "Add or open" mixes creating and navigating', 'Plan → Budgets (view picker + one Add button)', 'budgets'],
  ['Plan', 'Budget detail, rollover, shared, alerts threshold, expiry', 'Budget row', '—', 'Same', 'budget:bu2'],
  ['Plan', 'Seasonal templates (Ramadan, Eid, Summer), budget suggestions', 'Hidden in Budget toolbar menu', 'Undiscoverable', 'Budgets → Suggestions and Templates sections', 'budgets'],
  ['Plan', 'Bills & subscriptions (calendar, waste, price changes, auto-pay check)', 'Dashboard sheet, Budget menu, Debt → Bills tab', 'Three entry points, two presentations', 'Plan → Bills & Subscriptions (one screen)', 'bills'],
  ['Plan', 'Record bill payment', 'Bill detail', '—', 'Bill detail → Record payment', 'bill:bl1'],
  ['Plan', 'Savings goals, contributions, auto-save reminders, round-ups', 'Accounts module grid; Add Goal in Budget menu', 'Split across two tabs', 'Plan → Goals', 'goals'],
  ['Plan', 'Income — salary, freelance, rental, dividends, passive, stability score', 'Budget toolbar menu', 'Hidden in a menu', 'Plan → Income', 'income'],
  ['Plan', 'Debt — overview, loans, snowball/avalanche, calculator, lent, borrowed, BNPL, card utilisation', 'Budget menu and Accounts grid', 'Two entry points; ten chip tabs', 'Plan → Debt (Overview, Payoff plan, People, BNPL)', 'debt'],
  ['Plan', 'Family — household budget, child allowances, shared goals, permissions, members', 'Settings → Family', 'A module inside Settings', 'Plan → Household', 'family'],
  ['Plan', 'Planning tools: AI CFO, Retirement, Life events, Estate, Smart cash, Education', 'Settings → Premium Features', 'Modules inside Settings', 'Plan → Planning tools', 'tools'],
  ['Wealth', 'Net worth headline (one shared definition)', 'Accounts hero', '—', 'Wealth tab hero', 'wealth'],
  ['Wealth', 'Accounts (bank, savings, cash, wallets, credit cards) and account detail', 'Accounts tab, inner tab 1', 'Mixed with holdings in four inner tabs', 'Wealth → grouped list → Account', 'account:a1'],
  ['Wealth', 'Loan detail, record payment, amortisation', 'Account / Debt', '—', 'Wealth → Loans and Plan → Debt', 'loan:l1'],
  ['Wealth', 'Net worth dashboard — history, forecast, allocation, milestones, snapshots', 'Sheet from Accounts', 'A primary destination opened as a modal', 'Wealth → Net worth (pushed)', 'networth'],
  ['Wealth', 'Investments — holdings, crypto, gold, allocation, performance, dividends, capital gains, scenarios, simulation', 'Accounts → Portfolio (10 chip tabs)', 'Ten tabs in a scrolling chip row', 'Wealth → Investments (Holdings + Analysis list)', 'investments'],
  ['Wealth', 'Real estate, vehicles, personal and digital assets', 'Accounts → Assets & Liabilities', 'Name promises liabilities it doesn\'t show', 'Wealth → Property & assets', 'assets'],
  ['Wealth', 'Gift cards and loyalty programmes', 'Accounts inner tab "Other"', 'Hidden under "Other"', 'Wealth → Cards & rewards', 'rewards'],
  ['Insights', 'Reports (13) with PDF/CSV export', 'Dashboard icon button', 'Unlabelled icon', 'Home → Reports; sidebar on wide screens', 'reports'],
  ['Insights', 'AI assistant tools: anomalies, coach, patterns, savings, balance forecast, bill negotiation, ESG, digital twin', 'Dashboard sparkle icon', 'Separate from Financial Intelligence; two health scores', 'Home → Insights (one hub)', 'insights'],
  ['Insights', 'Financial health score and predictions', 'Settings → Financial Intelligence', 'Inside Settings', 'Insights → Health score', 'insight:health'],
  ['Insights', 'Ask (rule-based chat)', 'AI hub → chat sheet', '—', 'Insights → Ask', 'sheet:ask'],
  ['Search', 'In-app search across records and features', '— (Spotlight only)', 'No way to find a feature by name', 'Search tab: transactions, accounts, bills, goals and every screen/setting', 'search'],
  ['Settings', 'Profile name, base currency', 'Settings', '—', 'Settings → Profile / Currency', 'settings'],
  ['Settings', 'Face ID, passcode (PIN), auto-lock, security score', 'Settings (inline toggles) + Security subpage', 'Same controls in two places', 'Settings → Face ID & Passcode (one place)', 'security'],
  ['Settings', 'Notifications (bills, budgets 75/90/100%, low balance, large purchase, salary, goals, digests)', 'Settings → Notifications', '—', 'Same; permission-denied state', 'notifications'],
  ['Settings', 'Appearance — theme, OLED, accent, high contrast, first weekday, fiscal year', 'Settings → Appearance', '—', 'Same', 'appearance'],
  ['Settings', 'Categories and auto-categorisation rules', 'Settings → sheets', '—', 'Settings → Categories & Rules (also "Manage" from the category picker)', 'categories'],
  ['Settings', 'On-device backup, email backup, import a backup file, restore', 'Settings → Data & Privacy', '—', 'Settings → Backup & Restore', 'backup'],
  ['Settings', 'Clear all data', 'Settings → Data & Privacy', 'One tap from other rows', 'Bottom of Backup & Restore, typed confirmation', 'backup'],
  ['Settings', 'Siri & Shortcuts phrases', 'Not shown in the app', 'Users can\'t discover phrases or automations', 'Settings → Siri & Shortcuts', 'siri'],
  ['Settings', 'About, privacy policy, terms', 'Settings', '—', 'Same', 'about'],
  ['App', 'Onboarding (name, base currency)', 'First launch', 'Four marketing pages before setup', 'Two steps: welcome, setup', 'scene:onboarding'],
  ['App', 'Lock screen (Face ID, PIN, lockout)', 'Launch / return', '—', 'Same', 'scene:lock'],
  ['App', 'Restore from device snapshot after reinstall', 'Launch', '—', 'Same', 'scene:restore'],
  ['System', 'Siri / Shortcuts intents: log expense/income, balance, budget, open section, SMS, Apple Pay', 'App Intents', 'Invisible inside the app', 'Unchanged intents + Settings → Siri & Shortcuts (simulated in prototype)', 'siri'],
  ['Hidden', 'Tax management, Business & freelancer, Remittance, Insurance, Collaborative planner, Audit log, Google Drive backup, PDF import, Two-factor', 'Hidden by DisableableFeature', 'Not user-visible today', 'Stay hidden; each has a reserved slot (Plan → Planning tools, Import, Security) for when it is re-enabled', 'tools'],
];
